version: '3'
services:
  py_app:
    build: ./py
    command: uvicorn main:app  --host 0.0.0.0 --reload
    environment:
      - FastAPI_ENV=development
    ports:
      - '8000:8000'
    volumes:
      - ./py:/home/py/app #:cached # <--- This will map ./py1 to /root/py1 inside the container.

  node_app:
    image: node:12.3-alpine
    user: "node"
    environment:
      - NODE_ENV=development
    command: "npm install && npm start" #npm install && npm install protobufjs && npm start
    ports:
      - '5000:5000'
    working_dir: /home/node/app
    volumes:
      - ./node:/home/node/app:cached # <--- This will map ./node_app to /root/node_app inside the container.
