version: '3'
services:
  py_app:
    build: ./py_app/
    command: sh -c "uvicorn /pyApp.main:app --reload"
    environment:
      - PORT=8000
      - FastAPI_ENV=development
    ports:
      - '8000:8000'
    working_dir: /pyApp
    volumes:
      - ./py_app:/pyApp:cached # <--- This will map ./py1 to /root/py1 inside the container.

  node_app:
    image: node:12.3-alpine
    command: sh -c "node index.js"
    environment:
      - NODE_ENV=development
      - PORT=5000
    ports:
      - '5000:5000'
    working_dir: /nodeApp
    volumes:
      - ./node_app:/nodeApp:cached # <--- This will map ./node_app to /root/node_app inside the container.
